run:
  timeout: 5m
  modules-download-mode: readonly
output:
  sort-results: true
linters-settings:
  depguard:
    rules:
      main:
        deny:
          - pkg: github.com/satori/go.uuid
            desc: Use github.com/google/uuid or github.com/gofrs/uuid instead
  errcheck:
    check-type-assertions: true
    check-blank: true
  gofumpt:
    extra-rules: true
  govet:
    enable-all: true
    disable:
      - composites
  misspell:
    locale: US
  staticcheck:
    checks: ["all", "-SA3000"]
linters:
  disable-all: true
  enable:
    - depguard
    - errcheck
    - errorlint
    - exportloopref
    - goconst
    - gofumpt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - noctx
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - typecheck
    - unconvert
    - unused
issues:
  max-same-issues: 10
  exclude-use-default: false
  exclude-dirs:
    - internal/ns
    - internal/skia
    - internal/w32
  exclude:
    - "package-comments: should have a package comment"
